[package]
name = "thesnakegame"
version = "0.1.9"
edition = "2021"

[dependencies]
bracket-lib = { git = "https://github.com/amethyst/bracket-lib.git" }
rand = "0.8.5"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3